name: Frontend Integration Tests CI/CD

# This workflow tests Angular frontend against actual FastAPI backend
# Backend repo: https://github.com/gurdaan/agentic-workflow-backend

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  # Integration Tests Job (Frontend + Backend)
  integration_tests:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Frontend Integration Tests
    
    steps:
      # Checkout Frontend Repository
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4

      # Checkout Backend Repository
      - name: Checkout Backend Repository
        uses: actions/checkout@v4
        with:
          repository: gurdaan/agentic-workflow-backend
          path: backend

      # Setup Python for Backend
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Setup Node.js for Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Install Backend Dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Add test runner origin to CORS allow list (temporary CI patch)
      - name: Patch Backend CORS For CI
        run: |
          if grep -q 'allow_origins=\[' backend/app.py; then
            echo "Patching CORS allow_origins with Karma origin..."
            # Insert localhost:9876 origins if not already present
            grep -q 'localhost:9876' backend/app.py || sed -i "s/allow_origins=\[/allow_origins=\[\n        \"http:\/\/localhost:9876\",\n        \"http:\/\/127.0.0.1:9876\",/" backend/app.py
            echo 'Updated allow_origins:'
            grep -n 'allow_origins=\[' -A5 backend/app.py
          else
            echo "Could not find allow_origins list in backend/app.py; skipping patch";
          fi

      # Start FastAPI Backend Server
      - name: Start FastAPI Backend
        run: |
          cd backend
          uvicorn app:app --host 0.0.0.0 --port 8000 &
          echo "Waiting for backend to start..."
          sleep 10
        env:
          PYTHONPATH: ./backend
          # Azure DevOps Configuration
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_ORGANIZATION_URL: ${{ secrets.AZURE_DEVOPS_ORGANIZATION_URL }}
          # Azure OpenAI Configuration
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          # AI Foundry Configuration
          AI_FOUNDRY_ENDPOINT: ${{ secrets.AI_FOUNDRY_ENDPOINT }}
          AI_FOUNDRY_PROJECT_NAME: ${{ secrets.AI_FOUNDRY_PROJECT_NAME }}
          AI_FOUNDRY_ASSISTANT_ID: ${{ secrets.AI_FOUNDRY_ASSISTANT_ID }}
          AI_FOUNDRY_TESTCASES_ASSISTANT_ID: ${{ secrets.AI_FOUNDRY_TESTCASES_ASSISTANT_ID }}
          AI_FOUNDRY_DEV_TASKS_ASSISTANT_ID: ${{ secrets.AI_FOUNDRY_DEV_TASKS_ASSISTANT_ID }}
          # Azure Resource Configuration
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_AI_PROJECT_NAME: ${{ secrets.AZURE_AI_PROJECT_NAME }}
          # Azure Storage Configuration
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}

      # Wait for Backend Health Check
      - name: Wait for Backend to be Ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:8000/health || curl -f http://localhost:8000/docs; do echo "Waiting for backend..."; sleep 2; done'
        continue-on-error: true

      # Verify Backend is Running
      - name: Verify Backend Health
        run: |
          echo "Testing backend health endpoint..."
          curl -f http://localhost:8000/health || echo "Health endpoint failed"
          echo "Testing backend docs endpoint..."
          curl -f http://localhost:8000/docs || echo "Docs endpoint failed"

      # Install Frontend Dependencies
      - name: Install Frontend Dependencies
        run: npm ci

      # Run Integration Tests (Frontend API calls against real backend)
      - name: Run Integration API Tests
        run: |
          # Override API base URL to point to local backend
          sed -i "s|baseUrl: 'http://0.0.0.0:8000'|baseUrl: 'http://localhost:8000'|g" src/environments/environment.ts
          # List test files to verify they exist
          echo "Available test files:"
          find . -name "*.spec.ts"
          # Run all tests (Angular config + tsconfig.spec.json now include tests directory)
          npx ng test --watch=false --browsers=ChromeHeadless --code-coverage || TEST_EXIT=$?
          # Detect zero-test scenario (Angular exits 0 but ran 0 tests) by checking coverage summary existence
          if ! grep -R "integration" coverage/* 2>/dev/null && [ -f coverage/lcov.info ]; then
            echo "⚠️ No integration test markers found in coverage. Ensure tests executed.";
          fi
          exit ${TEST_EXIT:-0}

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            coverage/
            karma.xml
            test-results.xml

  # Build and Deploy Job (only runs after tests pass)
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Frontend
    needs: [integration_tests]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build --if-present
        env:
          NODE_ENV: production

      - name: Build And Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MUD_0113ED00F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist/jonas-ai-agent"

  # Close PR Job
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MUD_0113ED00F }}
          action: "close"
